### ISSUE TITLE
Add Form Validator

### ISSUE THREAD

**Issue by AmolKumarGupta** [AmolKumarGupta/Up-finance-Backend#7]
1. Validate data in signup and login method 
2. Use [express-validator](https://www.npmjs.com/package/express-validator)

**Comment by AdeosunDeji** [comment]
First time contributing, looking to add the validator.

**Comment by AdeosunDeji** [comment]
I want to test on postman but I can't start the server cause you're running the dist folder. I don't want to change anything. How can i start the server?

**Comment by AmolKumarGupta** [comment]
@AdeosunDeji , You need to install dev dependencies
After that run this command
```basb
npm run dev
```

**Comment by AdeosunDeji** [comment]
still not starting the server. Just watching for file changes.

**Comment by AmolKumarGupta** [comment]
Ok. what node version you are using. my node verison is 18. may be it would be the reason.
did it create dist folder or not??

**Comment by AdeosunDeji** [comment]
v20 and the dist folder got created.  I could make a pull request and you test it. I'm sure it works
